- name: Runner Setup
  hosts: all
  become: yes
  tasks:
    - name: Install requests
      ansible.builtin.pip:
        name: requests
    - name: Pull GitHub Runner image
      containers.podman.podman_image:
        name: docker.io/sandeepkumar0088/github-runner:0088
#        name: docker.io/rkalluru/github-runner:d87
        pull: true
    - name: Runner container
      containers.podman.podman_container:
        name: "{{ item }}"
        image: docker.io/sandeepkumar0088/github-runner:0088
#        image: docker.io/rkalluru/github-runner:d87
        state: started
        recreate: true
        restart_policy: always
        security_opt:
          - label=disable
        volumes:
          - /run/podman/podman.sock:/var/run/docker.sock
        env:
          NAME: "{{ item }}"
          TOKEN: "{{ TOKEN }}"
          ORG: "https://github.com/sdevops5454"
      loop:
        - runner1
        - runner2
        - runner3
        - runner4
        - runner5
        - runner6
      register: out
      ignore_errors: yes